plugins {
	id 'fabric-loom' version '1.5-SNAPSHOT'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = 'modernminecarts-testmod'
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation project(path: ':', configuration: 'namedElements')
}

loom {
	runs {
		gametest {
			server()
			name 'Modern Minecarts Game Tests'
			vmArg '-Dfabric-api.gametest'
			vmArg "-Dfabric-api.gametest.report-file=${project.buildDir}/gametest-report.xml"
			runDir 'build/gametest'
		}
	}
}

processResources {
	inputs.property 'version', project.version

	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}
